### ISSUE TITLE
Some implementation problems

### ISSUE THREAD

**Issue by SuperMacholo** [Ren-Research/LOMAR#2]
Hello, thank you very much for providing the program code. I would like to ask how to generate the dataset, because the error below occurred during the execution of generate_data.py
![image](https://github.com/Ren-Research/LOMAR/assets/162671842/5a31abd4-7aec-482c-833e-9ae5120a450b)

**Comment by lipengfeizju** [comment]
As the message indicates, you can't generate a problem named "obm". When you run the `generate_data.py`, you should add some arguments to make sure it generates the correct graph with specific size and other configurations. A quick examples is

```shell
python data/generate_data.py --problem adwords --dataset_size 1000 \
    --dataset_folder dataset/train/adwords_triangular_uniform_0.10.4_10by100/parameter_-1 \
    --u_size 10 --v_size 60 --graph_family triangular --weight_distribution uniform \
    --weight_distribution_param 0.1 0.4 --graph_family_parameter -1 
```

More examples can be found here
https://github.com/Ren-Research/LOMAR/blob/main/TUTORIAL.md
